### ISSUE TITLE
Importing preset with non-default keyboard layout

### ISSUE THREAD

**Issue by crimsonvspurple** [dodekeract/manta-config-engine-app#56]
If you import preset with non-default keyboard layout (e.g., razer), even though razer is selected in settings, the layout visually loads the default one.

You need to go to settings, change from razer to default and then back to razer to see things properly.

**Comment by FlorianWendelborn** [comment]
Yeah, that sounds like it would happen the way I coded it. Easiest workaround is a reload though. It updates the app's state without checking if a new layout needs to be loaded.

I guess it can be fixed by adding this

```
setTimeout(function () {
    actions.loadKeyboardLayout();
}, 0);
```

to the top of the `PRESET_IMPORT_FILE` case in `store.js`.

If you could test that and submit another pull request in case this fixes the issue I'd be happy to merge/fix it now. Otherwise I'd test that in 1-2 days.

**Comment by FlorianWendelborn** [comment]
Oh, just looked into the code and that snipped needs to go right above the `store.emitChange()` call. Didn't remember this was one of the weird functions/cases.
