### ISSUE TITLE
Add option to load built-in presets without using file upload

### ISSUE THREAD

**Issue by crimsonvspurple** [dodekeract/manta-config-engine-app#58]
An option to load built-in presets without file upload download would be nice.

**Comment by FlorianWendelborn** [comment]
Yeah, especially since it already works for some presets. `blank.json` and `default.json` can be loaded in the Preset Viewer.

When I add that I'll probably try to make it linkable too, so that you could link to `https://manta.dodekeract.report/#/preset/dodekeract` and see an apply button or something like that.

Not sure how easy that's possible though.

I'm currently working on implementing `buy, item_tpscroll` and similar commands. Should be finished soon, at least the engine-part. May work on this issue afterwards.

**Comment by FlorianWendelborn** [comment]
@crimsonvspurple You should be able to update your preset now. Just make sure that you actually bump the version of it to `1.7.1` too.
